server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://  :3306/jpa_ch?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8
    username:
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create # 운영시에는 validate 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true

